name: Test
on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  nix-flake-check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Rebase on trunk
      if: ${{ !contains(github.ref, 'trunk') }}
      run: |
        git pull --rebase origin trunk

    - uses: dtolnay/rust-toolchain@stable
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: true

    - run: bundle exec rake
